# -*- coding: utf-8 -*-
"""
Módulo web/waf_detect
=====================
Fingerprinting de WAF (Web Application Firewall) basado en dos señales:

    1. Cabeceras y cookies características (cf-ray de Cloudflare,
       x-amzn-requestid de AWS WAF, cookies __cf_bm/incap/sucuri...).
    2. Respuesta del servidor ante una sonda clásica de SQLi: los WAF
       suelen devolver 403/406/429 con una página de bloqueo propia
       mientras el backend devolvería 200/500 normal.

Identifica: Cloudflare, AWS WAF, ModSecurity, Imperva/Incapsula, Sucuri,
Akamai y F5 BIG-IP. Si no coincide ninguno, se informa "sin WAF conocido".

Riesgo: MEDIO (envía una sonda de una sola petición al objetivo).
"""

import re

import requests

from core.base_module import BaseModulo, ModuloError

# Firmas: (nombre, función que decide a partir de (cabeceras, cuerpo))
SONDA = "?id=1%20OR%20%271%27%3D%271"
PESOS_BLOQUEO = {403, 406, 429, 501}


def _firmas(cabeceras, cuerpo: str) -> list:
    texto = " ".join(f"{k}: {v}" for k, v in cabeceras.items()).lower() + "\n" + cuerpo.lower()
    encontradas = []
    reglas = [
        ("Cloudflare", [r"cf-ray:", r"__cf_bm", r"cloudflare"]),
        ("AWS WAF", [r"x-amzn-requestid", r"awswaf"]),
        ("ModSecurity", [r"mod_security", r"modsecurity", r"this error was generated by mod_security"]),
        ("Imperva/Incapsula", [r"incap_ses", r"visid_incap", r"_incap_"]),
        ("Sucuri", [r"sucuri", r"x-sucuri-id"]),
        ("Akamai", [r"akamai", r"reference #[0-9a-f.]+"]),
        ("F5 BIG-IP", [r"bigipserver", r"ts=", r"the requested url was rejected"]),
    ]
    for nombre, patrones in reglas:
        if any(re.search(p, texto) for p in patrones):
            encontradas.append(nombre)
    return encontradas


class WafDetect(BaseModulo):
    """Detecta WAF frente a una URL mediante cabeceras y sonda de bloqueo."""

    NAME = "web/waf_detect"
    CATEGORIA = "web"
    DESCRIPCION = ("Fingerprinting de WAF (Cloudflare, AWS WAF, ModSecurity, "
                   "Imperva, Sucuri, Akamai, F5) por cabeceras/cookies y por "
                   "una sonda de bloqueo de una sola petición.")
    RIESGO = "medio"
    AUTOR = "REDHAVOC"
    REFERENCIA = "wafw00f (concepto, una sonda en lugar de 40)"

    def definir_opciones(self) -> None:
        self.opciones.declarar("URL", "", True, "URL objetivo (p. ej. http://acme.com/app)")
        self.opciones.declarar("SONDA", "true", False,
                               "true = enviar además la sonda de bloqueo (1 petición)")

    def ejecutar(self) -> dict:
        url = self.opt("URL").strip()
        if not url.startswith(("http://", "https://")):
            url = "http://" + url
        timeout = self.opt_int("TIMEOUT", 5) or 5
        usar_sonda = self.opt_bool("SONDA", True)

        sesion = requests.Session()
        sesion.headers["User-Agent"] = self._user_agent()

        # 1) Respuesta normal
        try:
            normal = sesion.get(url, timeout=timeout, allow_redirects=True)
        except requests.RequestException as err:
            raise ModuloError(f"No se puede acceder a {url} — {err}")
        cuerpo_normal = normal.text[:4000]
        firmas = _firmas(normal.headers, cuerpo_normal)

        # 2) Sonda de bloqueo
        estado_sonda = None
        bloqueada = False
        if usar_sonda:
            separador = "&" if "?" in url else "?"
            try:
                sonda = sesion.get(url + separador + SONDA, timeout=timeout,
                                   allow_redirects=False)
                estado_sonda = sonda.status_code
                firmas += _firmas(sonda.headers, sonda.text[:4000])
                bloqueada = (estado_sonda in PESOS_BLOQUEO
                             or "blocked" in sonda.text[:2000].lower()
                             or "security" in sonda.text[:2000].lower())
            except requests.RequestException:
                estado_sonda = None

        firmas = sorted(set(firmas))
        waf = firmas[0] if firmas else ("WAF desconocido (bloqueo genérico)"
                                        if bloqueada else "sin WAF conocido")

        resumen = f"{url} — WAF: {waf}"
        if estado_sonda is not None:
            resumen += f" · sonda: {estado_sonda}{' (bloqueada)' if bloqueada else ''}"

        return {
            "resumen": resumen,
            "url": url,
            "waf": waf,
            "firmas": firmas,
            "estado_normal": normal.status_code,
            "servidor": normal.headers.get("Server", "?"),
            "estado_sonda": estado_sonda,
            "sonda_bloqueada": bloqueada,
            "nota": ("El objetivo está tras WAF: los módulos web (sqli, dirs) "
                     "pueden ser bloqueados o registrados." if firmas or bloqueada
                     else "No se detectó WAF en la respuesta analizada."),
        }

    def _user_agent(self) -> str:
        try:
            global_opts = getattr(getattr(self, "ctx", None), "globales", None)
            if global_opts is not None:
                ua = global_opts.get("USER_AGENT", "")
                if ua:
                    return ua
        except Exception:  # noqa: BLE001
            pass
        try:
            from core import __version__
            return f"REDHAVOC/{__version__}"
        except Exception:  # noqa: BLE001
            return "REDHAVOC"
